---
version: 0.2

env:
  variables:
    CUCUMBER_FILTER_TAGS:
    THREADS: 2

phases:

  build:
    commands:
      - mvn clean verify -DthreadCount=${THREADS}
  post_build:
    commands:
      - OUTPUT_DIR=$(date +%F)/${CODEBUILD_BUILD_NUMBER} && mkdir -p ${OUTPUT_DIR}
      - mv target/surefire-reports ui-automation-reports-${CODEBUILD_BUILD_NUMBER}
      - zip -r ${OUTPUT_DIR}/surefire-reports-${CODEBUILD_BUILD_NUMBER}.zip ui-automation-reports-${CODEBUILD_BUILD_NUMBER}
      - mv ui-automation-reports-${CODEBUILD_BUILD_NUMBER}/-index.html ${OUTPUT_DIR}/test-results-${CODEBUILD_BUILD_NUMBER}.html
reports:
  test-report:
    base-directory: ui-automation-reports-${CODEBUILD_BUILD_NUMBER}

artifacts:
  files:
    - '**/surefire-reports-${CODEBUILD_BUILD_NUMBER}.zip'
    - '**/test-results-${CODEBUILD_BUILD_NUMBER}.html'

cache:
  paths:
    - /root/.m2/repository/**/*