name: Build the test pack

on: [ push ]

#on:
#  pull_request:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
      - name: Build and run framework tests
        run: mvn verify -Dtest=frameworkTests.**